version: '3.9'
services:
  rabbitmq:
    image: rabbitmq:3.8-management
    environment:
      RABBITMQ_DEFAULT_USER: "bhut"
      RABBITMQ_DEFAULT_PASS: "bhut"
    ports:
      - '5672:5672'
      - '15672:15672'
  mongodb:
    image: mongo:latest
    container_name: mongo-container
    hostname: localhost
    ports:
      - '27017:27017'


